name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - name: Install modules
        run: npm ci
      - name: Debug test environment
        run: |
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Test files found:"
          find test -name "*.test.*" | sort
          echo "Jest config:"
          cat jest.config.cjs

      - name: Prepare Jest cache
        run: npm run testCacheCreate
        continue-on-error: true

      - name: Run tests with verbose output
        run: npm test -- --verbose